[package]
name = "yahoo-weather"
version = "0.1.0"
authors = ["Robert Schütte <schuetterobert@gmail.com>"]

[dependencies]
quick-error = "1.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4.0", features = ["serde"] }
hyper = "0.10.9"
