[package]
name = "yahoo-weather"
version = "0.1.0"
authors = ["Robert Schütte <schuetterobert@gmail.com>"]

[dependencies]
quick-error = "1.1"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
chrono = { version = "0.3", features = ["serde"] }
curl = "0.4"
